### ISSUE TITLE
No sensitive_spreadSheet_data.txt

### ISSUE THREAD

**Issue by thomakl** [horstmannmat/FacebookPagePoster#1]
Hi

I'm confused with the guide you proposed : I can't find the file sensitive_spreadSheet_data.txt.
To what does the spreadsheet refer ?

`$ python download_spotted.py --noauth_local_webserver
Traceback (most recent call last):`

`  File "download_spotted.py", line 34, in <module>
    f = open('sensitive_spreadSheet_data.txt', 'r')
IOError: [Errno 2] No such file or directory: 'sensitive_spreadSheet_data.txt'`

Thank you for your time,

**Comment by horstmannmat** [comment]
I created the sensitive_spreadSheet_data.txt to store the id from my google spreadsheet. [`There is more information here `](https://developers.google.com/sheets/api/guides/concepts#spreadsheet_id)

**Comment by thomakl** [comment]
I may misunderstood something. Why do we need to access a google spreadsheet ? What does this document contains ?
I don't understant why we need those to access Twitter then Facebook.
By the way, I got a message from Twitter recently, they ended their connection with Facebook post. 
Does your module succed to post a message on Facebook recently ?

Thank your for your time,

**Comment by horstmannmat** [comment]
In my case, I have a Spreadsheet on google docs, with the messages that I want to post, so I use the google API to to download it first.
I used to post on Twitter and then my twitter account posted on Facebook, but unfortunately, they ended two weeks ago and I was unable use it anymore, so I developed using selenium.
I use it every day, and it is working fine, the selenium driver has some bugs, for example: write two messages in the same post, but you just need to make the firefox window visible

**Comment by horstmannmat** [comment]
I updated the readme file, I removed the twitter part, that I dont use it anymore, and added a sensitive_spreadSheet_data.txt example file.

I have another repository with a 'twitter way' to post https://github.com/horstmannmat/spottedposterviatwitter
