### ISSUE TITLE
Question -  It is possible to upload a picture?

### ISSUE THREAD

**Issue by thomakl** [horstmannmat/FacebookPagePoster#2]
Hi,

Your module works perfectly.
I'm asking myself if you found a way to put a picture in the post in Facebook  ?

Thanks

**Comment by horstmannmat** [comment]
I've nerver tried, but I think with some changes it may be possible. I found a similar repository using it. [here](https://github.com/fatih-koc/facebook-group-poster/blob/master/post.py).

Be free to contribute.

**Comment by horstmannmat** [comment]
In the method open_text_area() you need to insert this peace of code:
 ```python
   upload_button =  WebDriverWait(self.driver, 20).until(EC.presence_of_element_located((By.CSS_SELECTOR, "[data-testid='photo-video-button']")))
   upload_button.click()
   upload_photo = WebDriverWait(self.driver, 20).until(EC.presence_of_element_located((By.CSS_SELECTOR, "[data-testid='media-attachment-add-photo']")))
   upload_photo.send_keys("path/to/photo.jpg")
```

**Comment by horstmannmat** [comment]
Reopening to be visible to anyone with same doubt

**Comment by gumdropsteve** [comment]
Working on a similar project and came across yours @horstmannmat , looking like it might help fix a few issues I've struggled with -- thank you!

**Comment by horstmannmat** [comment]
You are welcome. Read the issue #1 to understand why I use the google API on this particular project, and why you can wrap off this part the code.

I've made some modifications to run faster and lighter (using m.facebook), so probably, the code above, to upload a picture, needs be modified. 

Any question you can open another issue, or email me.

**Comment by horstmannmat** [comment]
Closing issue, I've created a method to post **ONE** image, with text. 
So this issue don't need to be open anymore

You can still comment here :)
